### ISSUE TITLE
Does not BFS

### ISSUE THREAD

**Issue by ivan-w** [codenotary/vcn#81] opened 2020-02-21 11:37 UTC
When going into the GIT directory and typing "make" I get this :
ivan@db08:~/vChain/vcn$ make
go build -ldflags '-s -X github.com/vchain-us/vcn/pkg/meta.version=v0.8.3 -X github.com/vchain-us/vcn/pkg/meta.gitCommit=8e8d0e3564e52f8e9a423504d405aafbb1991b44 -X github.com/vchain-us/vcn/pkg/meta.gitBranch=master -X github.com/vchain-us/vcn/pkg/meta.version=v0.8.3-dev' ./cmd/vcn
go: finding github.com/prometheus/prometheus v1.7.2-0.20170814170113-3101606756c5
go: finding github.com/spf13/viper v1.4.0
go: finding github.com/syndtr/goleveldb v1.0.0
go: finding github.com/ethereum/go-ethereum v1.8.27
go: finding github.com/gorilla/handlers v1.4.2
go: finding github.com/pkg/browser v0.0.0-20180916011732-0a3d74bf9ce4
go: finding github.com/pborman/uuid v1.2.0
go: finding github.com/google/go-cmp v0.3.1
go: finding github.com/fjl/memsize v0.0.0-20190710130421-bcb5799ab5e5
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/hashicorp/golang-lru v0.5.3
go: finding github.com/tyler-smith/go-bip39 v1.0.2
go: finding github.com/urfave/cli v1.22.1
go: finding github.com/cmars/basen v0.0.0-20150613233007-fe3947df716e
go: finding github.com/gorilla/mux v1.7.3
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /home/ivan/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: finding github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/dghubble/sling v1.3.0
go: finding github.com/huin/goupnp v1.0.0
go: finding github.com/FactomProject/btcutilecc v0.0.0-20130527213604-d3a63a5752ec
go: finding github.com/blang/semver v3.5.1+incompatible
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/h2non/filetype v1.0.10
go: finding github.com/deckarep/golang-set v1.7.1
go: finding github.com/tyler-smith/go-bip32 v0.0.0-20170922074101-2c9cfd177564
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/onsi/gomega v1.4.3
go: finding google.golang.org/grpc v1.21.0
go: finding github.com/ugorji/go v1.1.4
go: finding github.com/magiconair/properties v1.8.0
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/jackpal/go-nat-pmp v1.0.1
go: finding github.com/rs/cors v1.7.0
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/opencontainers/go-digest v1.0.0-rc1
go: finding github.com/fsnotify/fsnotify v1.4.7
go: finding github.com/grpc-ecosystem/grpc-gateway v1.9.0
go: finding github.com/google/btree v1.0.0
go: finding golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: finding github.com/pelletier/go-toml v1.2.0
go: finding github.com/tmc/grpc-websocket-proxy v0.0.0-20190109142713-0ad062ec5ee5
go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding github.com/google/uuid v1.0.0
go: finding github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
go: finding github.com/karalabe/hid v0.0.0-20181128192157-d815e0c1a2e2
go: finding github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/stretchr/objx v0.1.1
go: finding github.com/allegro/bigcache v1.2.1
go: finding github.com/jonboulle/clockwork v0.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding go.uber.org/zap v1.10.0
go: finding github.com/spf13/jwalterweatherman v1.0.0
go: finding github.com/mattn/go-colorable v0.1.2
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/gorilla/websocket v1.4.0
go: finding github.com/soheilhy/cmux v0.1.4
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/caarlos0/spin v1.1.0
go: finding github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
go: finding github.com/fatih/color v1.7.0
go: finding go.etcd.io/bbolt v1.3.2
go: finding github.com/FactomProject/basen v0.0.0-20150613233007-fe3947df716e
go: finding github.com/spf13/cobra v0.0.5
go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: finding gopkg.in/src-d/go-git.v4 v4.13.1
go: finding github.com/aristanetworks/goarista v0.0.0-20190409234242-46f4bc7b73ef
go: finding github.com/coreos/bbolt v1.3.2
go: finding github.com/prometheus/client_golang v0.9.3
go: finding github.com/jbenet/go-base58 v0.0.0-20150317085156-6237cf65f3a6
go: finding github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/coreos/go-semver v0.2.0
go: finding github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: finding github.com/rjeczalik/notify v0.9.2
go: finding github.com/onsi/ginkgo v1.7.0
go: finding github.com/edsrzf/mmap-go v1.0.0
go: finding go.uber.org/atomic v1.4.0
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/cespare/cp v1.1.1
go: finding go.uber.org/multierr v1.1.0
go: finding gopkg.in/natefinch/npipe.v2 v2.0.0-20160621034901-c1b8fa8bdcce
go: finding github.com/coreos/etcd v3.3.10+incompatible
go: finding github.com/btcsuite/btcd v0.0.0-20190410025418-9bfb2ca0346b
go: finding github.com/spf13/afero v1.1.2
go: finding github.com/hashicorp/hcl v1.0.0
go: error loading module requirements
make: *** [Makefile:27: vcn] Error 1

**What happened**

The utility did not build

**What you expected to happen**

The executable to be built

**How to reproduce it (as minimally and precisely as possible)**

Simple debian install (go, gcc, gmake installed) - git clone, make.

**Environment**

Irrelevant  - the vcn executable is not built.

**Comment by mmeloni** [comment] 2020-04-25 12:35
Thanks @ivan-w . I was unable to reproduce. What's your GO version?

**Comment by ivan-w** [comment] 2020-04-25 13:43
Lemme check out the various versions. A the time of the test, I might have been running into a frankdebian issue.

**Comment by ivan-w** [comment] 2020-04-25 13:51
Getting this at this point !
ivan@db08:~/vChain/vcn$ make
go build -ldflags '-s -X github.com/vchain-us/vcn/pkg/meta.version=v0.8.3 -X github.com/vchain-us/vcn/pkg/meta.gitCommit=aaa8969b12579c0c931bcf5acf11e29ecfcd4b77 -X github.com/vchain-us/vcn/pkg/meta.gitBranch=master -X github.com/vchain-us/vcn/pkg/meta.version=v0.8.3-dev' ./cmd/vcn
go: finding github.com/jessevdk/go-flags v1.4.0
go: finding github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: finding github.com/emirpasic/gods v1.12.0
go: finding github.com/mattn/go-isatty v0.0.8
go: finding github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: finding github.com/stretchr/objx v0.2.0
go: finding golang.org/x/crypto v0.0.0-20190701094942-4def268fd1a4
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /home/ivan/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: finding golang.org/x/sys v0.0.0-20180926160741-c2ed4eda69e7
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190412213103-97732733099d
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150
go: finding github.com/xanzy/ssh-agent v0.2.1
go: finding golang.org/x/net v0.0.0-20190724013045-ca1201d0de80
go: finding golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1
go: finding github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
go: finding golang.org/x/text v0.3.2
go: finding github.com/alcortesm/tgz v0.0.0-20161220082320-9c5fe88206d7
go: finding github.com/google/go-cmp v0.3.0
go: finding github.com/pelletier/go-buffruneio v0.2.0
go: finding github.com/anmitsu/go-shlex v0.0.0-20161002113705-648efa622239
go: finding github.com/gliderlabs/ssh v0.2.2
go: finding github.com/src-d/gcfg v1.4.0
go: finding golang.org/x/tools v0.0.0-20190729092621-ff9f1409240a
go: finding github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: finding gopkg.in/src-d/go-git-fixtures.v3 v3.5.0
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding gopkg.in/src-d/go-billy.v4 v4.3.2
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: error loading module requirements


ivan@db08:~/vChain/vcn$ go version
go version go1.11.6 linux/amd64

**Comment by ivan-w** [comment] 2020-04-25 13:53
It's probably a 'go' package dependency plugins issue... I need to check on that

**Comment by mmeloni** [comment] 2020-04-25 15:12
Thanks @ivan-w . Please try  last GO version or 1.13 at least. I just tried to build without success with go.1.11.6. Please let me know

**Comment by dmacvicar** [comment] 2021-03-10 22:34
Closing. Please reopen if you can reproduce with a newer Go.

**Closed by dmacvicar** 2021-03-10 22:34 UTC
Labels: bug
